/** UI labels/tone for audit actions — shared between user activity and admin views. */
export const AUDIT_ACTION_LABELS: Record<string, { label: string }> = {
	"account.sign_in": { label: "Signed in" },
	"account.sign_out": { label: "Signed out" },
	"account.password_changed": { label: "Password changed" },
	"account.email_changed": { label: "Email change requested" },
	"account.2fa_enabled": { label: "2FA enabled" },
	"account.2fa_disabled": { label: "2FA disabled" },
	"impersonation.started": { label: "Account accessed by administrator" },
	"leave.applied": { label: "Leave request submitted" },
	"leave.decided": { label: "Leave request decided" },
	"issue.justification_submitted": { label: "Justification submitted" },
	"issue.reviewed": { label: "Issue reviewed" },
	"settings.schedule_updated": { label: "Work schedule updated" },
	"settings.holiday_added": { label: "Holiday added" },
	"settings.holiday_removed": { label: "Holiday removed" },
	"settings.member_role_changed": { label: "Member role changed" },
	"billing.subscribed": { label: "Plan subscribed" },
	"billing.topup_approved": { label: "Top-up approved" },
	"billing.topup_rejected": { label: "Top-up rejected" },
	"billing.downgraded": { label: "Downgraded to Free" },
};

export const AUDIT_TONE_CLASS: Record<string, string> = {
	"account.sign_in": "text-foreground",
	"account.sign_out": "text-muted-foreground",
	"account.password_changed": "text-foreground",
	"account.email_changed": "text-foreground",
	"account.2fa_enabled": "text-emerald-600 dark:text-emerald-400",
	"account.2fa_disabled": "text-amber-600 dark:text-amber-400",
	"impersonation.started": "text-destructive",
	"leave.applied": "text-foreground",
	"leave.decided": "text-foreground",
	"issue.justification_submitted": "text-foreground",
	"issue.reviewed": "text-foreground",
	"settings.schedule_updated": "text-muted-foreground",
	"settings.holiday_added": "text-muted-foreground",
	"settings.holiday_removed": "text-muted-foreground",
	"settings.member_role_changed": "text-muted-foreground",
	"billing.subscribed": "text-foreground",
	"billing.topup_approved": "text-emerald-600 dark:text-emerald-400",
	"billing.topup_rejected": "text-destructive",
	"billing.downgraded": "text-destructive",
};
